version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    tty: true 
    working_dir: /var/www
    volumes:
      - ./:/var/www

  webserver:
    image: nginx:stable
    container_name: webserver
    restart: always
    ports:
      - "8080:80"
    
    volumes:
      - ./:/var/www
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
  
  # db:
  #   image: "mysql:5.7"
  #   container_name: db
  #   restart: always
  #   volumes:
  #     - "/docker/initdb.sql:/docker-entrypoint-initdb.d/1.sql"
  #   environment:
  #     MYSQL_ROOT_USER: ${DB_USER}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_USER}
  #   ports:
  #     - "3306:3306" 
  #   expose:
  #     - 3306
 