version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    tty: true 
    working_dir: /var/www
    volumes:
      - ./:/var/www

  webserver:
    image: nginx:stable
    container_name: webserver
    restart: always
    ports:
      - "8080:80"
    
    volumes:
      - ./:/var/www
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

 